url: http://micael.carlstedt.com
baseurl: 

collections: 
  - posts
  - contracts
  - menuitems
  - services

# Site settings
title: Micael Carlstedt Consulting
email: micael@carlstedt.com
phone: +46722009494
description: "Micael Carlstedt Consulting AB"

# Company staff
people:
- name: Micael Carlstedt
  pic: 1
  position: CEO/Consultant
  social:
    - title: twitter
      url: https://twitter.com/micaelcarlstedt
    - title: linkedin
      url: https://www.linkedin.com/in/micaelcarlstedt
    - title: stack-overflow
      url: #

social:
  name: Micael Carlstedt
  links:
    - https://twitter.com/micaelcarlstedt
    - https://github.com/micaelcarlstedt
    - https://bitbucket.org/micael
    - https://www.linkedin.com/in/micaelcarlstedt
    - https://stackoverflow.com/story/micael

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social-networks:
  - title: linkedin
    url: https://www.linkedin.com/in/micaelcarlstedt
  - title: twitter
    url: https://twitter.com/micaelcarlstedt
  - title: bitbucket 
    url: https://bitbucket.org/micael
  - title: github
    url: https://github.com/micaelcarlstedt
  - title: stack-overflow
    url: https://stackoverflow.com/story/micael

# Postal address (add as many lines as necessary)
address:
  - line: Repslagaregatan 8a
  - line: 211 21, Malmö
  - line: Sweden

# Build settings
markdown: kramdown
permalink: pretty


plugins:
  - jekyll-seo-tag
  - jekyll-email-protect # https://github.com/vwochnik/jekyll-email-protect